### ISSUE TITLE
Background streching instead of scaling

### ISSUE THREAD

**Issue by NinoHelfenstein** [mijorus/RelaxingClock#12]
If I set the background to unsplashed or bing it stretches instead of scaling. Looks really ugly on screens that arent 16:9.
![screely-1716491363087](https://github.com/mijorus/RelaxingClock/assets/116466829/0e040e6e-f9a9-42b6-8a70-ae4fe072a67c)

Btw, really nice webapp

**Comment by mijorus** [comment]
Fixed, thank you

**Comment by NinoHelfenstein** [comment]
Keep it up 🚀
