### ISSUE TITLE
Website is down may be??

### ISSUE THREAD

**Issue by okarin001** [mijorus/RelaxingClock#2]
Can't access the website, always times out. Tested with different checkers. Says website not available. Is it down??

**Comment by mijorus** [comment]
Hi, DNS were migrating to a new provider, show be fine now

**Comment by okarin001** [comment]
> Hi, DNS were migrating to a new provider, should be fine now or in a matter of minutes

ohh, thanks a lot.. i couldn't wait and started using it locally. LMAO. 
<img src="https://media.giphy.com/media/LOEgEYZHyGbXY8KgA3/giphy.gif" width=100>
